Algoritmo "calculo_media_por_peso"

Var
matricula:caractere
nota1, nota2, nota3, resul: real
Inicio

 escreva("infoma a sua mátricula: ")
 leia(matricula)
 escreva("informa a primeira nota: ")
 leia(nota1)
 Escreva("informa a segunda nota: ")
 leia(nota2)
 escreva("informe a terceira nota: ")
 leia(nota3)
 resul <- ((nota1 * 0.2) + (nota2 * 0.3) + ( nota3 * 0.5))
 escreva ("A nota da matricula ", matricula, " é ", resul)

Fimalgoritmo